sonar.projectKey=Production-Grade-End-to-End-DevSecOps-Project
sonar.projectName=Production-Grade-End-to-End-DevSecOps-Project
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**
