name: Production Grade DevSecOps CI/CD Pipeline
on:
    push:
        branches:
            - QA
        paths:
            - 'client/**'
            - 'server/**'
            - '.github/workflows/qa-cicd.yml'

jobs:
    gitleaks-scan:
        name: Gitleaks Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Run Gitleaks scan
              run: |
                docker run --rm -v ${{ github.workspace }}:/repo \
                zricethezav/gitleaks:latest  \
                detect --source=/repo \
                --report-format json \
                --report-path=/repo/gitleaks-report.json \
                --redact \
                --exit-code 0

            - name: Upload Gitleaks report
              uses: actions/upload-artifact@v7
              with:
                name: gitleaks-report
                path: gitleaks-report.json
                if-no-files-found: warn
    
    chekov-terraform-scan:
        name: Checkov Terraform Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Python Setup
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install Checkov
              run: pip install checkov

            - name: Run Checkov scan
              run: |
                checkov -d . \
                --framework terraform \
                --quiet --output json > checkov-report.json || true

            - name: Upload Checkov report
              uses: actions/upload-artifact@v7
              with:
                name: checkov-report
                path: checkov-report.json
                if-no-files-found: warn


    checkov-kubernetes-scan:
        name: Checkov Kubernetes Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Python Setup
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install Checkov
              run: pip install checkov

            - name: Run Checkov scan
              run: |
                checkov -d . \
                --framework kubernetes \
                --quiet --output json > checkov-k8s-report.json || true

            - name: Upload Checkov report
              uses: actions/upload-artifact@v7
              with:
                name: checkov-k8s-report
                path: checkov-k8s-report.json
                if-no-files-found: warn

    chekov-dockerfile-scan:
        name: Checkov Dockerfile Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Python Setup
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install Checkov
              run: pip install checkov

            - name: Run Checkov scan
              run: |
                checkov -d . \
                --framework dockerfile \
                --quiet --output json > checkov-dockerfile-report.json || true

            - name: Upload Checkov report
              uses: actions/upload-artifact@v7  
              with:
                name: checkov-dockerfile-report
                path: checkov-dockerfile-report.json
                if-no-files-found: warn

    client-trivy-fs-scan:
        name: Client Trivy FS Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Install Trivy
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                version: latest
                cache: true

            - name: Verify Trivy installation
              run: |
                trivy --version
                which trivy
             
            - name: Run Trivy scan on client directory
              run: |
                trivy fs ./client \
                --format json \
                --output trivy-client-report.json \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0

            - name: Run Trivy scan on server directory
              run: |
                trivy fs ./client \
                --format table \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0 > trivy-client-report.txt

            - name: Upload Trivy reports
              uses: actions/upload-artifact@v7
              with:
                name: trivy-client-json-report
                path: trivy-client-report.json
                if-no-files-found: warn

            - name: Upload Trivy text report
              uses: actions/upload-artifact@v7
              with:
                name: trivy-client-table-report
                path: trivy-client-report.txt
                if-no-files-found: warn
    
    server-trivy-fs-scan:
        name: Server Trivy FS Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Install Trivy
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                version: latest
                cache: true

            - name: Verify Trivy installation
              run: |
                trivy --version
                which trivy
             
            - name: Run Trivy scan on server directory
              run: |
                trivy fs ./server \
                --format json \
                --output trivy-server-report.json \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0

            - name: Run Trivy scan on server directory (text format)
              run: |
                trivy fs ./server \
                --format table \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0 > trivy-server-report.txt

            - name: Upload Server Trivy JSON reports
              uses: actions/upload-artifact@v7
              with:
                name: trivy-server-json-report
                path: trivy-server-report.json
                if-no-files-found: warn

            - name: Upload Server Trivy Table report
              uses: actions/upload-artifact@v7
              with:
                name: trivy-server-table-report
                path: trivy-server-report.txt
                if-no-files-found: warn