name: Production Grade DevSecOps CI/CD Pipeline
on:
    push:
        branches:
            - QA
        paths:
            - 'client/**'
            - 'server/**'
            - '.github/workflows/qa-cicd.yml'

jobs:
    gitleaks-scan:
        name: Gitleaks Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Run Gitleaks scan
              run: |
                docker run --rm -v ${{ github.workspace }}:/repo \
                zricethezav/gitleaks:latest  \
                detect --source=/repo \
                --report-format json \
                --report-path=/repo/gitleaks-report.json \
                --redact \
                --exit-code 0

            - name: Upload Gitleaks report
              uses: actions/upload-artifact@v7
              with:
                name: gitleaks-report
                path: gitleaks-report.json
                if-no-files-found: warn
    
    chekov-terraform-scan:
        name: Checkov Terraform Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Python Setup
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install Checkov
              run: pip install checkov

            - name: Run Checkov scan
              run: |
                checkov -d . \
                --framework terraform \
                --quiet --output json > checkov-report.json || true

            - name: Upload Checkov report
              uses: actions/upload-artifact@v7
              with:
                name: checkov-report
                path: checkov-report.json
                if-no-files-found: warn


    chekov-kubernetes-scan:
        name: Checkov Kubernetes Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Python Setup
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install Checkov
              run: pip install checkov

            - name: Run Checkov scan
              run: |
                checkov -d . \
                --framework kubernetes \
                --quiet --output json > checkov-k8s-report.json || true

            - name: Upload Checkov report
              uses: actions/upload-artifact@v7
              with:
                name: checkov-k8s-report
                path: checkov-k8s-report.json
                if-no-files-found: warn

    chekov-dockerfile-scan:
        name: Checkov Dockerfile Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Python Setup
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install Checkov
              run: pip install checkov

            - name: Run Checkov scan
              run: |
                checkov -d . \
                --framework dockerfile \
                --quiet --output json > checkov-dockerfile-report.json || true

            - name: Upload Checkov report
              uses: actions/upload-artifact@v7  
              with:
                name: checkov-dockerfile-report
                path: checkov-dockerfile-report.json
                if-no-files-found: warn

    client-trivy-fs-scan:
        name: Client Trivy FS Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Install Trivy
              uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
              with:
                version: latest
                cache: true

            - name: Verify Trivy installation
              run: |
                trivy --version
                which trivy
             
            - name: Run Trivy scan on client directory
              run: |
                trivy fs ./client \
                --format json \
                --output trivy-client-report.json \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0

            - name: Run Trivy scan on server directory
              run: |
                trivy fs ./client \
                --format table \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0 > trivy-client-report.txt

            - name: Upload Trivy reports
              uses: actions/upload-artifact@v7
              with:
                name: trivy-client-json-report
                path: trivy-client-report.json
                if-no-files-found: warn

            - name: Upload Trivy text report
              uses: actions/upload-artifact@v7
              with:
                name: trivy-client-table-report
                path: trivy-client-report.txt
                if-no-files-found: warn
    
    server-trivy-fs-scan:
        name: Server Trivy FS Scan
        runs-on: ubuntu-latest
        needs: gitleaks-scan
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Install Trivy
              uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
              with:
                version: latest
                cache: true

            - name: Verify Trivy installation
              run: |
                trivy --version
                which trivy
             
            - name: Run Trivy scan on server directory
              run: |
                trivy fs ./server \
                --format json \
                --output trivy-server-report.json \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0

            - name: Run Trivy scan on server directory (text format)
              run: |
                trivy fs ./server \
                --format table \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0 > trivy-server-report.txt

            - name: Upload Server Trivy JSON reports
              uses: actions/upload-artifact@v7
              with:
                name: trivy-server-json-report
                path: trivy-server-report.json
                if-no-files-found: warn

            - name: Upload Server Trivy Table report
              uses: actions/upload-artifact@v7
              with:
                name: trivy-server-table-report
                path: trivy-server-report.txt
                if-no-files-found: warn

    client-eslint-scan:
        name: Client ESLint Scan
        runs-on: ubuntu-latest
        needs: 
            - client-trivy-fs-scan
            - chekov-terraform-scan
            - chekov-kubernetes-scan    
            - chekov-dockerfile-scan
        defaults:
          run:
            working-directory: client
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: client/package-lock.json

            - name: Install dependencies
              run: |
                npm ci

            - name: Run ESLint scan
              run: |
                npm run lint --if-present
                continue-on-error || true

    server-eslint-scan:
        name: Server ESLint Scan
        runs-on: ubuntu-latest
        needs: 
            - server-trivy-fs-scan
            - chekov-terraform-scan
            - chekov-kubernetes-scan    
            - chekov-dockerfile-scan
        defaults:
          run:
            working-directory: server
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: server/package-lock.json

            - name: Install dependencies
              run: |
                npm ci

            - name: Run ESLint scan
              run: |
                npm run lint --if-present
                continue-on-error || true

    client-unit-tests:
        name: Client Unit Tests
        runs-on: ubuntu-latest
        needs: 
            - client-eslint-scan
        defaults:
          run:
            working-directory: client
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: client/package-lock.json

            - name: Install dependencies
              run: |
                npm ci

            - name: Run unit tests
              run: |
                npm test --if-present
                continue-on-error || true

    server-unit-tests:
        name: Server Unit Tests
        runs-on: ubuntu-latest
        needs: 
            - server-eslint-scan    
        defaults:
          run:      
            working-directory: server
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4 

            - name: Setup Node.js
              uses: actions/setup-node@v6     
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: server/package-lock.json

            - name: Install dependencies
              run: |
                npm ci

            - name: Run unit tests
              run: |
                npm test --if-present
                continue-on-error || true
                
    sonarqube-scan:
        name: SonarQube Analysis
        runs-on: ubuntu-latest
        continue-on-error: true
        needs: 
            - client-unit-tests
            - server-unit-tests
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  # Fetch all history for accurate analysis

            - name: SonarQube Quality Gate Status
              id: sonar-quality-gate-check
              uses: sonarsource/sonarqube-scan-action@master
              with:
                polling-timeout-seconds: 600
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

            - name: Example step to demonstrate how to use the output of the SonarQube Quality Gate check
              run: |
                echo "SonarQube Quality Gate Status: ${{ steps.sonar-quality-gate-check.outputs.quality-gate-status }}"
    
    frontend-client-build:
        name: Frontend Build
        runs-on: ubuntu-latest
        needs: 
            - client-unit-tests
        defaults:
          run:
            working-directory: client
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: client/package-lock.json

            - name: Install client dependencies
              run: |
                npm ci

            - name: Build frontend application
              run: |
                npm run build --if-present

    docker-build-and-push:
        name: Docker Build and Push
        runs-on: ubuntu-latest
        needs: 
            - frontend-client-build

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build and push
              uses: docker/build-push-action@v7
              with:
                load: true
                push: false
                tags: prashantrock777/nodejs-app:${{github.sha}}
                
            - name: Install Trivy
              uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
              with:
                version: latest
                cache: true

            - name: Verify Trivy installation
              run: |
                trivy --version
                which trivy

            - name: Run Trivy scan on Docker image
              run: |
                trivy image prashantrock777/nodejs-app:${{ github.sha }} \
                --format json \
                --output trivy-docker-image-report.json \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0

            - name: Run Trivy scan on Docker image (Table format)
              run: |
                trivy image prashantrock777/nodejs-app:${{ github.sha }} \
                --format table \
                --severity CRITICAL,HIGH \
                --ignore-unfixed \
                --exit-code 0 > trivy-docker-image-report.txt

            - name: Upload Trivy Docker image JSON report
              uses: actions/upload-artifact@v7  
              with:
                name: trivy-docker-image-json-report
                path: trivy-docker-image-report.json
                if-no-files-found: warn

            - name: Upload Trivy Docker image Table report
              uses: actions/upload-artifact@v7
              with:
                name: trivy-docker-image-table-report 
                path: trivy-docker-image-report.txt
                if-no-files-found: warn

            - name: Push Docker image to Docker Hub
              run: |
                docker push prashantrock777/nodejs-app:${{ github.sha }}
                docker push prashantrock777/nodejs-app:latest